### PR TITLE
update pynco version to 0.3

### PR DESCRIPTION
**Pull request by jhamman**

### CODE REVIEW

**Comment by jhamman** [comment]
@ocefpaf - first time updating the pynco feedstock and I'm getting some build failures. Can you help me see what is going wrong?

**Comment by ocefpaf** [comment]
You  need to update the checksum  (sha256) and it would be a good idea to rerender with conda-smithy too. (I in transit with only phone and 3g I can help you further once I get back.)

**Comment by jhamman** [comment]
@ocefpaf - have you been seeing circleci hang like this?

**Comment by ocefpaf** [comment]
CircleCi hook failed in a few PR this past week but the build passed. It is ok to merge.

**Pull request merged**
